token_list.append({"lexeme": "integer","category": "KEYWORD","line": 1})
# token_list.append({"lexeme": "a","category": "IDENTIFIER", "line": 1})
# token_list.append({"lexeme": "=","category": "OPERATOR","line": 1})
# token_list.append({"lexeme": "3","category": "NUMBER","line": 1})
# token_list.append({"lexeme": ";","category": "DELIMITER","line": 1})
# token_list.append({"lexeme": "integer","category": "KEYWORD","line": 1})
# token_list.append({"lexeme": "a","category": "IDENTIFIER", "line": 1})
# token_list.append({"lexeme": "=","category": "OPERATOR","line": 1})
# token_list.append({"lexeme": "3","category": "NUMBER","line": 1})
# token_list.append({"lexeme": ";","category": "DELIMITER","line": 1})
# token_list.append({"lexeme": "}","category": "OPEN_CURLY_BRACE","line": 1})